### ISSUE TITLE
Install Latest Refactor - ImportError: cannot import name 'CUSTOM_BROWSER' (circular import)

### ISSUE THREAD

**Issue by callmenemo491** [makarworld/litewax#7]
when doing:
``` # sudo pip install git+https://github.com/makarworld/litewax.git@refactoring ```

get error:
```
Collecting git+https://github.com/makarworld/litewax.git@refactoring
  Cloning https://github.com/makarworld/litewax.git (to revision refactoring) to /tmp/pip-req-build-u3daoy3h
  Running command git clone --filter=blob:none --quiet https://github.com/makarworld/litewax.git /tmp/pip-req-build-u3daoy3h
  Running command git checkout -b refactoring --track origin/refactoring
  Switched to a new branch 'refactoring'
  Branch 'refactoring' set up to track remote branch 'refactoring' from 'origin'.
  Resolved https://github.com/makarworld/litewax.git to commit e468ff396936ab59fb0d00065c032da6fa31ccf3
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [14 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-req-build-u3daoy3h/setup.py", line 2, in <module>
          from litewax import __version__
        File "/tmp/pip-req-build-u3daoy3h/litewax/__init__.py", line 1, in <module>
          from .contract import Contract, Action
        File "/tmp/pip-req-build-u3daoy3h/litewax/contract.py", line 4, in <module>
          from .types import ContractInterface
        File "/tmp/pip-req-build-u3daoy3h/litewax/types.py", line 5, in <module>
          from .baseclients import AnchorClient, WCWClient
        File "/tmp/pip-req-build-u3daoy3h/litewax/baseclients.py", line 7, in <module>
          from .types import CUSTOM_BROWSER
      ImportError: cannot import name 'CUSTOM_BROWSER' from partially initialized module 'litewax.types' (most likely due to a circular import) (/tmp/pip-req-build-u3daoy3h/litewax/types.py)
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

**Comment by makarworld** [comment]
fixed now
